### ISSUE TITLE
Git remote branch name

### ISSUE THREAD

**Issue by Simon-Jarke** [meshcloud/unipipe-service-broker#40]
I want to change the git remote branch name form master to main. The documentation says the environment variable to do this is GIT_REMOTE-BRANCH, which is appearently not a valid environment variable name.

az container create --file ./deployment.yaml  
(InvalidContainerEnvironmentVariable) The environment variable name in container 'xx' of container group 'xx' is invalid. A valid environment variable name must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName').

I also tried GIT_REMOTE_BRANCH, however it seems that it does not get pulled into the program.

**Comment by JohannesRudolph** [comment]
Hi @Simon-Jarke thanks for reporting this issue! The configuration properties are bound from environment variables using [relaxed binding](https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding), so `GIT_REMOTE_BRANCH` should work. It's also used that way in the [UniPipe ACI deployment example](
https://github.com/meshcloud/unipipe-service-broker/wiki/2.-Deploy-a-Azure-Container-Group-for-Universal-Pipeline-Service-Broker---Caddy-(SSL)).

I just did a quick review of the code in `GitHandlerService.kt` that does the git interactions and from a quick glance it looks like it uses the configured remote branch name in all the relevant places. 

> I also tried GIT_REMOTE_BRANCH, however it seems that it does not get pulled into the program.

How did you determine that? You should see during startup of the OSB either one of these lines revealing the configured branch name in the log:

```
log.info { "Branch $branchName exists." }
...
log.info { "Branch $branchName does not exist locally. Creating it." }
```

What does your unipipe instance log print?

**Comment by Simon-Jarke** [comment]
Hey @JohannesRudolph, here is what the log shows:

2021-09-24 07:58:47.939  INFO 22 --- [           main] i.m.dockerosb.DockerOsbApplicationKt     : Starting DockerOsbApplicationKt on wk-caas-2a62a0da64c74b729203004ed9b19bf6-b6df4b3bd1f4c96f769fe4 with PID 22 (/app/generic-osb-api-1.0.0.jar started by root in /app)
2021-09-24 07:58:47.947  INFO 22 --- [           main] i.m.dockerosb.DockerOsbApplicationKt     : No active profile set, falling back to default profiles: default
2021-09-24 07:58:55.837  INFO 22 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8075 (http)
2021-09-24 07:58:55.863  INFO 22 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-09-24 07:58:55.863  INFO 22 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.36]
2021-09-24 07:58:56.166  INFO 22 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-09-24 07:58:56.167  INFO 22 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7924 ms
2021-09-24 07:58:59.161 ERROR 22 --- [           main] i.m.d.service.GenericCatalogService      : Could not read catalog.yml file from '/app/tmp/git/catalog.yml'. Will start with an empty catalog.
2021-09-24 07:58:59.753  INFO 22 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@2532b351, org.springframework.security.web.context.SecurityContextPersistenceFilter@511505e7, org.springframework.security.web.header.HeaderWriterFilter@3f92c349, org.springframework.security.web.authentication.logout.LogoutFilter@6e0f7aad, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@749ab7b4, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@15fdd1f2, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@2a389173, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@4349754, org.springframework.security.web.session.SessionManagementFilter@70e02081, org.springframework.security.web.access.ExceptionTranslationFilter@5e4fa1da, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@12f8b1d8]
2021-09-24 07:59:00.546  INFO 22 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-09-24 07:59:01.757  INFO 22 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2021-09-24 07:59:01.970  INFO 22 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8075 (http) with context path ''
2021-09-24 07:59:02.052  INFO 22 --- [           main] i.m.dockerosb.DockerOsbApplicationKt     : Started DockerOsbApplicationKt in 16.285 seconds (JVM running for 18.207)
2021-09-24 07:59:25.734  INFO 22 --- [nio-8075-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-09-24 07:59:25.735  INFO 22 --- [nio-8075-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-09-24 07:59:25.748  INFO 22 --- [nio-8075-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 13 ms
2021-09-24 08:02:44.237 ERROR 22 --- [nio-8075-exec-9] .s.c.ServiceBrokerWebMvcExceptionHandler : Unknown exception handled: 

org.eclipse.jgit.api.errors.RefNotAdvertisedException: Remote origin did not advertise Ref for branch master. This Ref may not exist in the remote or may be hidden by permission settings.
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:317) ~[org.eclipse.jgit-4.11.0.201803080745-r.jar!/:4.11.0.201803080745-r]
	at io.meshcloud.dockerosb.persistence.GitHandler.pull(GitHandler.kt:62) ~[classes!/:na]
	at io.meshcloud.dockerosb.service.GenericCatalogService.getLatestCatalog(GenericCatalogService.kt:43) ~[classes!/:na]
	at io.meshcloud.dockerosb.service.GenericCatalogService.getCatalog(GenericCatalogService.kt:51) ~[classes!/:na]
	at org.springframework.cloud.servicebroker.controller.CatalogController.getCatalog(CatalogController.java:57) ~[spring-cloud-open-service-broker-core-3.1.1.RELEASE.jar!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]

And here the relevant part of the deployment.yml:

 - name: genericosb
    properties:
      image: ghcr.io/meshcloud/unipipe-service-broker:v1.0.6
      ports:
      - port: 8075
        protocol: TCP
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      environmentVariables:
        - name: GIT_REMOTE
          secureValue: https://github.com/Freudenberg-Co/CIT-CF-Services.git
        - name: GIT_REMOTE_BRANCH
          secureValue: main
        - name: GIT_USERNAME
          secureValue: 
        - name: GIT_PASSWORD
          secureValue: 
        - name: APP_BASIC_AUTH_USERNAME
          secureValue: 
        - name: APP_BASIC_AUTH_PASSWORD
          secureValue:

**Comment by JohannesRudolph** [comment]
Thanks that was helpful. Looks like unipipe is not considering the configured remote branch name when fetching the catalog (as opposed to reading/writing service instances). This is most definitely a bug in the broker.

**Comment by JohannesRudolph** [comment]
Maybe I was a bit too fast on this :-) 

I noticed the line numbers in your stacktraces are off - and indeed you're on `unipipe-service-broker:v1.0.6`. Can you try running this on the latest `unipipe-service-broker:v1.2.0`?

**Comment by Simon-Jarke** [comment]
Just tried but now I get this:

2021-09-24 12:22:50.594  INFO 22 --- [           main] i.m.dockerosb.DockerOsbApplicationKt     : Starting DockerOsbApplicationKt on wk-caas-ded7bb0f662e4f94a7802194a6980f1d-6a76c5de60f2c6f4c46e47 with PID 22 (/app/generic-osb-api-1.0.0.jar started by root in /app)
2021-09-24 12:22:50.658  INFO 22 --- [           main] i.m.dockerosb.DockerOsbApplicationKt     : No active profile set, falling back to default profiles: default
2021-09-24 12:22:56.688  INFO 22 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8075 (http)
2021-09-24 12:22:56.763  INFO 22 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-09-24 12:22:56.764  INFO 22 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.36]
2021-09-24 12:22:56.981  INFO 22 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-09-24 12:22:56.982  INFO 22 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6117 ms
2021-09-24 12:23:04.301  INFO 22 --- [           main] i.m.d.persistence.GitHandlerService      : Branch main does not exist locally. Creating it.
2021-09-24 12:23:04.359  WARN 22 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genericCatalogService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/service/GenericCatalogService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitOperationContextFactory' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitOperationContextFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitHandlerService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitHandlerService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.meshcloud.dockerosb.persistence.GitHandlerService]: Constructor threw exception; nested exception is org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/main cannot be resolved
2021-09-24 12:23:04.372  INFO 22 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-09-24 12:23:04.393  INFO 22 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-09-24 12:23:04.462 ERROR 22 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'genericCatalogService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/service/GenericCatalogService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitOperationContextFactory' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitOperationContextFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitHandlerService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitHandlerService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.meshcloud.dockerosb.persistence.GitHandlerService]: Constructor threw exception; nested exception is org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/main cannot be resolved
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
	at io.meshcloud.dockerosb.DockerOsbApplicationKt.main(DockerOsbApplication.kt:15) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[generic-osb-api-1.0.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[generic-osb-api-1.0.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[generic-osb-api-1.0.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[generic-osb-api-1.0.0.jar:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitOperationContextFactory' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitOperationContextFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitHandlerService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitHandlerService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.meshcloud.dockerosb.persistence.GitHandlerService]: Constructor threw exception; nested exception is org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/main cannot be resolved
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:227) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitHandlerService' defined in URL [jar:file:/app/generic-osb-api-1.0.0.jar!/BOOT-INF/classes!/io/meshcloud/dockerosb/persistence/GitHandlerService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.meshcloud.dockerosb.persistence.GitHandlerService]: Constructor threw exception; nested exception is org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/main cannot be resolved
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:313) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:294) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 42 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.meshcloud.dockerosb.persistence.GitHandlerService]: Constructor threw exception; nested exception is org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/main cannot be resolved
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:309) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 56 common frames omitted
Caused by: org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/main cannot be resolved
	at org.eclipse.jgit.api.CreateBranchCommand.getStartPointObjectId(CreateBranchCommand.java:246) ~[org.eclipse.jgit-5.11.0.202103091610-r.jar!/:5.11.0.202103091610-r]
	at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:99) ~[org.eclipse.jgit-5.11.0.202103091610-r.jar!/:5.11.0.202103091610-r]
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:194) ~[org.eclipse.jgit-5.11.0.202103091610-r.jar!/:5.11.0.202103091610-r]
	at io.meshcloud.dockerosb.persistence.GitHandlerService$Companion.switchToBranchAndCreateIfMissing(GitHandlerService.kt:313) ~[classes!/:na]
	at io.meshcloud.dockerosb.persistence.GitHandlerService$Companion.initGit(GitHandlerService.kt:276) ~[classes!/:na]
	at io.meshcloud.dockerosb.persistence.GitHandlerService.<init>(GitHandlerService.kt:35) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41) ~[kotlin-reflect-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159) ~[kotlin-reflect-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112) ~[kotlin-reflect-1.5.0.jar!/:1.5.0-release-749 (1.5.0)]
	at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:798) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:189) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 58 common frames omitted
